version: '3'
services:
  stackover-be:
    container_name: stackover-be
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        port: ${PORT}
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    links: 
      - mongo
  mongo:
    container_name: mongo
    build:
      context: mongo/
      dockerfile: Dockerfile
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    ports:
      - "27017:27017"
    env_file:
      - .env
