version: '3'
services:
  mongo:
    container_name: mongo
    build:
      context: mongo/
      dockerfile: Dockerfile
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    ports:
      - "27017:27017"
    env_file:
      - .env
  mongo-express:
    container_name: mongo_express
    restart: always
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - me.env
    links:
      - mongo
  stackover-be:
    container_name: stackover-be
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        port: ${PORT}
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    links: 
      - mongo
