version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
  mongo-express:
    container_name: mongo_express
    restart: always
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ../me.env
    links:
      - mongo